# Project: Game
# Makefile created by Dev-C++ 5.4.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Player.o Compass.o main.o Enemy.o
LINKOBJ  = Player.o Compass.o main.o Enemy.o
LIBS     = -L"C:/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -lopengl32 -lglu32 -lglut32
INCS     = -I"C:/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW32/include"
BIN      = Game.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Player.o: Player.cpp
	$(CPP) -c Player.cpp -o Player.o $(CXXFLAGS)

Compass.o: Compass.cpp
	$(CPP) -c Compass.cpp -o Compass.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Enemy.o: Enemy.cpp
	$(CPP) -c Enemy.cpp -o Enemy.o $(CXXFLAGS)
